#!/bin/sh
# CoalMine pre-push hook (Unix)
# Generated by CoalMine
# Exit on failure to prevent push

if [ -f scripts/verify.mjs ]; then
  # Single guarded node-test gate (existsSync precheck + orphan check + fail-loud);
  # scripts/test.mjs owns the test list so CI and the hooks cannot drift apart.
  node scripts/test.mjs || exit 1
  # PowerShell parity tests (shared ps-config + the spawned rot-canary PS hooks) — skip
  # if pwsh is absent so the gate still runs on a box without PowerShell; fail loud when present.
  if command -v pwsh >/dev/null 2>&1; then
    pwsh -NoProfile -File scripts/lib/ps-config.test.ps1 || exit 1
    pwsh -NoProfile -File scripts/lib/ps-hooks.test.ps1 || exit 1
  fi
  node scripts/verify.mjs
  exit $?
fi
exit 0
